### PR TITLE
Update netlify.toml

### PR DESCRIPTION
**Pull request by rahultrivedi180**
Enable CORS.

### CODE REVIEW

**Comment by danielkellyio** [comment]
What’s the use case for enabling CORS?

**Comment by rahultrivedi180** [comment]
@danielkellyio I deployed [my site](https://guideonline.in) on Netlify with a domain that I purchased and it was giving me cors errors. And this code solved the issue. So I thought template should be cors ready.

**Comment by rahultrivedi180** [comment]
Even [deploy preview](https://deploy-preview-13--awake-template.netlify.com/) has cors errors.

**Comment by danielkellyio** [comment]
My knowledge on CORS is limited but for security's sake I don't want to open it up without good reason. I'm not seeing any errors on my builds, could you provide some screenshots with the exact error? Thanks!

**Comment by rahultrivedi180** [comment]
> My knowledge on CORS is limited but for security's sake I don't want to open it up without good reason. I'm not seeing any errors on my builds, could you provide some screenshots with the exact error? Thanks!

Please check this [link](https://deploy-preview-13--awake-template.netlify.com/). Open the link and see the console. CORS errors will be there. Same thing happens when you connect netlify deployment to a custom purchased domain.

**Comment by lArtiquel** [comment]
Hi, today i've got this error -->
image
Looks like netlify now redirecting from .com top-level domain to .app for some reason. But get requests are still going thru .com/api/whatever.
And thanks for sharing this awesome template!

> My knowledge on CORS is limited but for security's sake I don't want to open it up without good reason. I'm not seeing any errors on my builds, could you provide some screenshots with the exact error? Thanks!

**Comment by lArtiquel** [comment]
Ok, i see that you are doing this relative requests at <code>cms/netlify/mixins.js</code>
```javascript
     const resources = await this.axios.$get(`api/${this.slugPlural}.json`)
```
So, i think, that the best solution just to change top-level site domain from .com to .app in your netlify profile settings

> Hi, today i've got this error -->
> image
> Looks like netlify now redirecting from .com top-level domain to .app for some reason. But get requests are still going thru .com/api/whatever.
> And thanks for sharing this awesome template!
> 
> > My knowledge on CORS is limited but for security's sake I don't want to open it up without good reason. I'm not seeing any errors on my builds, could you provide some screenshots with the exact error? Thanks!

**Comment by danielkellyio** [comment]
Since it's a netlify sub-domain I didn't see where I was able to actually change the site name but I was able to just manually set the URL environment variable like so:

Screen Shot 2020-04-15 at 1 22 21 PM

(usually this env variable is auto set by netlify)

**Comment by danielkellyio** [comment]
thanks @lArtiquel for pointing this out!

**Pull request closed without merging**
